name: Node.js CI

on:
  push:
    branches:
      - main

jobs:

  test:
    name: Test & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Use build cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.astro
            ${{ github.workspace }}/.jampack
          key: ${{ runner.os }}-astro-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-astro-${{ hashFiles('**/package-lock.json') }}-
      - name: Use Yarn cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Verify
        run: make verify
      - name: Build
        run: make
      - name: 'Deploy to Netlify'
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEPLOY_TOKEN }}
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_command: ':'
          install_command: ':'
          build_directory: 'dist/'
